import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home page</h1>
      <div>
        <Link href="/" scroll={false}>
          Egyptian Cotton
        </Link>
        <Link href="/" scroll={false}>
          Silk
        </Link>
        <Link href="/" scroll={false}>
          Ankara
        </Link>
        <Link href="/" scroll={false}>
          Adire
        </Link>
      </div>
      <div>
        <div name="/">1</div>
        <div name="/">2</div>
        <div name="/">3</div>
        <div name="/">4</div>
      </div>
    </div>
  );
}
